[project]
name = "bybit-announcements-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.21.1",
    "tabulate>=0.9.0",
]
